env:
  node: true
  es2021: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'


parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  prettier/prettier:
    - error
    - singleQuote: true
    # - endOfLine: auto
    - indent: 2

